<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new Employee';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('admin', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('first_name')).'&nbsp;';
 echo $this->formRow($form->get('last_name'));
 echo $this->formRow($form->get('email_id'));
 echo $this->formRow($form->get('phone_no'));
 echo $this->formRow($form->get('status'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();