<?php
 // module/Album/view/album/album/delete.phtml:

 $title = 'Delete Employee';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete Employee 
     '<?php echo $this->escapeHtml($employee->first_name); ?>
     
      <?php 	echo $this->escapeHtml($employee->last_name); ?>'
     ?
 </p>
 <?php
 $url = $this->url('admin', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $employee->id; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>